### ISSUE TITLE
Import error when running docker

### ISSUE THREAD

**Issue by JuliaWasala** [flaviostutz/sentinelloader#17]
Hiya, I just set up to user your docker container because my kernel suddenly started dying when running getRegionHistory (yesterday it worked fine, I triggered the LTA retrieval, and today the files are shown to be online but the kernel dies during execution of getREgionHistory),

But when importing sentinelloader I get the following error:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-9268305e3050>", line 4, in <module>
    from sentinelloader import Sentinel2Loader

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "/usr/local/lib/python3.5/dist-packages/sentinelloader-1.1.1-py3.5.egg/sentinelloader/__init__.py", line 1, in <module>
    from .sentinel2loader import Sentinel2Loader

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible

  File "/usr/local/lib/python3.5/dist-packages/sentinelloader-1.1.1-py3.5.egg/sentinelloader/sentinel2loader.py", line 1, in <module>
    from sentinelsat import SentinelAPI

  File "/usr/local/lib/python3.5/dist-packages/sentinelsat-1.1.0-py3.5.egg/sentinelsat/__init__.py", line 4, in <module>
    from . import sentinel

  File "/usr/local/lib/python3.5/dist-packages/sentinelsat-1.1.0-py3.5.egg/sentinelsat/sentinel.py", line 287
    self.logger.info(f"Found {count:,} products")
                                               ^
SyntaxError: invalid syntax
```

**Comment by flaviostutz** [comment]
Sorry, I didn’t get it. Are you using the same container or made some changes to it?

Syntax error maybe cause by using a different Python runtime or something (Python 2.7 vs 3.4, for example), but I am only guessing in the dark.

Check the dependencies on Dockerfile.

**Comment by JuliaWasala** [comment]
I'm using the same container, I set it up following the instructions in the readme.

I did get my own environment working in the end, but the docker container still isn't. I don't need the docker anymore, but  I thought you would like to know if it wasn't working!
